
platform :ios, '12.0'

target 'YZXUIKit_Example' do
  pod 'YZXUIKit', :path => '../'
  
  pod 'LookinServer', :configurations => ['Debug']

  target 'YZXUIKit_Tests' do
    inherit! :search_paths

    
  end
end
